# Check that everything (tests, benches, etc) builds in std environments
precheck_steps: &precheck_steps
  docker:
    - image: jamwaffles/circleci-embedded-graphics:1.40.0-cimg
      auth:
        username: jamwaffles
        password: $DOCKERHUB_PASSWORD
  steps:
    - checkout
    - restore_cache:
        key: v1-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
    - run: rustup default ${RUST_VERSION:-stable}
    - run: rustup component add rustfmt
    - run: cargo update
    - run: just build
    - save_cache:
        key: v1-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cargo.toml" }}
        paths:
          - ./target
          - /home/circleci/.cargo/registry

version: 2
jobs:
  precheck-stable:
    <<: *precheck_steps
  precheck-beta:
    environment:
      - RUST_VERSION: "beta"
    <<: *precheck_steps

build_jobs: &build_jobs
  jobs:
    - precheck-stable
    - precheck-beta

workflows:
  version: 2
  build_all:
    <<: *build_jobs
