name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - run: cargo build

  build-no-sdl:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - run: cargo build --no-default-features

  check-formatting-and-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-readme
      - uses: actions/checkout@v4
      - run: cargo fmt --check
      - run: just check-readme
